pages:
  stage: deploy
  image: python:latest
  script:
    - pip install -r requirements.txt
    - python build_page.py docs/assets/software.csv docs/
    - mkdocs build --site-dir public
  artifacts:
    expire_in: 5 minutes
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
